### ISSUE TITLE
ZoomRectangleManipulator fails if the plot model changes during zoom

### ISSUE THREAD

**Issue by csabar** [oxyplot/oxyplot#1076]
If I drag the mouse zoom rectangle and during this zoom the tab changes, then the handler throws NullReferenceException.

### Steps to reproduce

1. Place the plot view on a tab
2. Make a timer, when the timer expires, switch the actual tab. Of course this is just an example. Real use case can be showing a tab with warnings, or other important thing.
3. Before automatic switching drag the plot to show zoom rectangle and move during dragging
4. When the tab switches it throws an exception

Platform: WPF
.NET version: 4.5

### Expected behaviour

Ignore the mouse move

### Actual behaviour

Throws Null reference exception

    System.NullReferenceException: Object reference not set to an instance of an object.
       at OxyPlot.ZoomRectangleManipulator.Delta(OxyMouseEventArgs e)
       at OxyPlot.ControllerBase.HandleMouseMove(IView view, OxyMouseEventArgs args)
       at OxyPlot.Wpf.PlotBase.OnMouseMove(MouseEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       ...

### Solution
Check `Source\OxyPlot\PlotController\Manipulators\ZoomRectangleManipulator.cs` for possible null references.

**Comment by objorke** [comment]
could this be a race condition - do we need to lock with the sync root object?
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/PlotController/Manipulators/ZoomRectangleManipulator.cs#L78
