### ISSUE TITLE
System.ArgumentNullException when clicking around wildly

### ISSUE THREAD

**Issue by cmorty** [oxyplot/oxyplot#1208]
### Steps to reproduce
1) Constantly add and remove Wpf.LineSeries (These are live traces - Scope-like)
2) Wpf.LineSeries get their data via an  ObservableCollection<DataPoint>
3) The collection can be empty and also change over time (not all points are added at the end)
4) Click around wildly
5) System.ArgumentNullException

Platform:
.NET version: 4.7

### Expected behaviour

Should not crash.

### Actual behaviour

```
System.ArgumentNullException
  HResult=0x80004003
  Nachricht = Der Wert darf nicht NULL sein.
  Quelle = System.Core
  Stapelüberwachung:
   at System.Linq.Enumerable.Skip[TSource](IEnumerable`1 source, Int32 count)
   at OxyPlot.Series.XYAxisSeries.GetNearestPointInternal(IEnumerable`1 points, Int32 startIdx, ScreenPoint point) in C:\projects\oxyplot\Source\OxyPlot\Series\XYAxisSeries.cs:line 339
   at OxyPlot.Series.DataPointSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate) in C:\projects\oxyplot\Source\OxyPlot\Series\DataPointSeries.cs:line 102
   at OxyPlot.Series.LineSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate) in C:\projects\oxyplot\Source\OxyPlot\Series\LineSeries.cs:line 317
   at OxyPlot.Series.Series.HitTestOverride(HitTestArguments args) in C:\projects\oxyplot\Source\OxyPlot\Series\Series.cs:line 158
   at OxyPlot.Model.<HitTest>d__9.MoveNext() in C:\projects\oxyplot\Source\OxyPlot\Graphics\Model.cs:line 67
   at OxyPlot.Model.HandleMouseDown(Object sender, OxyMouseDownEventArgs e) in C:\projects\oxyplot\Source\OxyPlot\Graphics\Model.MouseEvents.cs:line 87
   at OxyPlot.ControllerBase.HandleMouseDown(IView view, OxyMouseDownEventArgs args) in C:\projects\oxyplot\Source\OxyPlot\Graphics\ControllerBase.cs:line 82
   at OxyPlot.Wpf.PlotBase.OnMouseDown(MouseButtonEventArgs e) in C:\projects\oxyplot\Source\OxyPlot.Wpf\PlotBase.Events.cs:line 114
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at LiciVisGui.App.Main()

```

### Suggested soltion

Add an additional null check to `DataPointSeries:GetNearestPoint()`, to make shure `this.ActualPoints` is not null.

E.g. : https://github.com/cmorty/oxyplot/commit/62abd37b0d77e749f6f0057e7962d9b5ce783376

**Comment by SkinnySackboy** [comment]
We are experiencing a similar issue:

`System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Skip[TSource](IEnumerable`1 source, Int32 count)
   at OxyPlot.Series.XYAxisSeries.GetNearestPointInternal(IEnumerable`1 points, Int32 startIdx, ScreenPoint point)
   at OxyPlot.Series.DataPointSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate)
   at OxyPlot.Series.LineSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate)
   at OxyPlot.PlotModel.GetSeriesFromPoint(ScreenPoint point, Double limit)
   at OxyPlot.TrackerManipulator.Delta(OxyMouseEventArgs e)
   at OxyPlot.ControllerBase.HandleMouseMove(IView view, OxyMouseEventArgs args)
   at OxyPlot.Wpf.PlotBase.OnMouseMove(MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

It looks like somehow this method is sometimes called with the points argument being null.

**Comment by Jonarw** [comment]
How do you specify your data points? Are you using the `ItemsSource` or the `Points` property?

**Comment by SkinnySackboy** [comment]
@Jonarw apologies for the delay - using the Points property.

**Comment by heinersuter** [comment]
I had the same issue in my plot when the contained 0 points.
Solved it by calling `PlotModel.InvalidatePlot(true);` with parameter `true `instead of `false`.
