### ISSUE TITLE
XYAxisSeries.GetNearestPointInternal is not thread safe

### ISSUE THREAD

**Issue by aderzuib** [oxyplot/oxyplot#1482]
### Steps to reproduce

In an application where an oxyplot is shown as a WPF component, a mouse click was made into the plot. The bug occured only once and could not be reproduced.

Platform: Windows 10
.NET version: 4.7.2

### Expected behaviour

No exception should be thrown

### Actual behaviour

An InvalidOperationException was thrown. The stack trace is

Ausnahmeinformationen: System.InvalidOperationException
   bei System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
   bei System.Collections.Generic.List`1+Enumerator[[OxyPlot.DataPoint, OxyPlot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=638079a8f0bd61e9]].MoveNextRare()
   bei System.Collections.Generic.List`1+Enumerator[[OxyPlot.DataPoint, OxyPlot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=638079a8f0bd61e9]].MoveNext()
   bei System.Linq.Enumerable+<SkipIterator>d__31`1[[OxyPlot.DataPoint, OxyPlot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=638079a8f0bd61e9]].MoveNext()
   bei OxyPlot.Series.XYAxisSeries.GetNearestPointInternal(System.Collections.Generic.IEnumerable`1<OxyPlot.DataPoint>, Int32, OxyPlot.ScreenPoint)
   bei OxyPlot.Series.DataPointSeries.GetNearestPoint(OxyPlot.ScreenPoint, Boolean)
   bei OxyPlot.Series.LineSeries.GetNearestPoint(OxyPlot.ScreenPoint, Boolean)
   bei OxyPlot.TrackerManipulator.GetNearestHit(OxyPlot.Series.Series, OxyPlot.ScreenPoint, Boolean, Boolean)
   bei OxyPlot.TrackerManipulator.Delta(OxyPlot.OxyMouseEventArgs)
   bei OxyPlot.ControllerBase.HandleMouseMove(OxyPlot.IView, OxyPlot.OxyMouseEventArgs)
   bei OxyPlot.Wpf.PlotBase.OnMouseMove(System.Windows.Input.MouseEventArgs)
   bei System.Windows.UIElement.OnMouseMoveThunk(System.Object, System.Windows.Input.MouseEventArgs)
   bei System.Windows.Input.MouseEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   bei System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   bei System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   bei System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   bei System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   bei System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   bei System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   bei System.Windows.Application.RunDispatcher(System.Object)
   bei System.Windows.Application.RunInternal(System.Windows.Window)
   bei System.Windows.Application.Run(System.Windows.Window)
   bei System.Windows.Application.Run()

It looks like during line 300 in XYAxisSeries.cs, the collection is manipulated. Because of this, the exception is thrown in line 1173 of List<T>, because the versions of the list and the enumerator are not equal anymore.

Line number in the source code of List<T> is from https://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs

**Comment by DShaurin** [comment]
This issue leads to application crash and you cannot handle the exception thrown since it goes directly to UI thread.
***Reliable Steps to reproduce***
Create a plot with some LineSeries
```csharp
var plot = new PlotModel();
var lineSeries = new LineSeries();
plot.Series.Add(lineSeries);
// arrange Axes, add the plot to a form, etc.
// Then modify lineSeries.Points collection in a separate thread
Task.Factory.StartNew(()=>
{
    var lastPoint = new DataPoint(1,2);
    while (true)
    {
        lastPoint = new DataPoint(lastPoint.X+0.1,lastPoint.Y+0.1);
        lineSeries.Points.Add(new DataPoint());
        if (lineSeries.Points.Count>1000)
            lineSeries.Points.RemoveRange(0,500);
    }
});
while(true){
    Thread.Sleep(500);
    plot.InvalidatePlot(true);
}
```
Run the app and do many left mouse button clicks and moves on the plot. I'll get a crash very soon.

***Actual behaviour***
Second chance exception is:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SkipIterator>d__31`1.MoveNext()
   at OxyPlot.Series.XYAxisSeries.GetNearestPointInternal(IEnumerable`1 points, Int32 startIdx, ScreenPoint point) in D:\Repos\oxyplot\Source\OxyPlot\Series\XYAxisSeries.cs:line 300
   at OxyPlot.Series.DataPointSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate) in D:\Repos\oxyplot\Source\OxyPlot\Series\DataPointSeries.cs:line 102
   at OxyPlot.Series.LineSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate) in D:\Repos\oxyplot\Source\OxyPlot\Series\LineSeries.cs:line 317
   at OxyPlot.TrackerManipulator.GetNearestHit(Series series, ScreenPoint point, Boolean snap, Boolean pointsOnly) in D:\Repos\oxyplot\Source\OxyPlot\PlotController\Manipulators\TrackerManipulator.cs:line 142
   at OxyPlot.TrackerManipulator.Delta(OxyMouseEventArgs e) in D:\Repos\oxyplot\Source\OxyPlot\PlotController\Manipulators\TrackerManipulator.cs:line 103
   at OxyPlot.ControllerBase.HandleMouseMove(IView view, OxyMouseEventArgs args) in D:\Repos\oxyplot\Source\OxyPlot\Graphics\ControllerBase.cs:line 166
   at OxyPlot.Wpf.PlotBase.OnMouseMove(MouseEventArgs e) in D:\Repos\oxyplot\Source\OxyPlot.Wpf\PlotBase.Events.cs:line 129
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Appp.App.Main()

**Comment by VisualMelon** [comment]
I don't think I quite understand what is going on here (I'll have to test it myself once I'm less distracted), but is the cross over between the Events and the Updating code or the code modifying the Collection? I'd expect this to go wrong eventually even without user input. The controller is meant to avoid crossover between Events and mode Update, but the code modifying the collection also needs to take the SyncRoot, otherwise it can always interfere.

**Comment by devel0** [comment]
```cs
lock (model.SyncRoot)
{
  // add point to serie
}
```

worked for me
