### ISSUE TITLE
System.ArgumentNullException when PlotController event is fired on WinForm startup and using the series ItemSource property

### ISSUE THREAD

**Issue by Corey11820** [oxyplot/oxyplot#1844]
### Steps to reproduce

Happens when using WinForms and uses LineSeries ItemSource property.  I haven't tested on WPF or any other platform.

1. Create a WinForms app using code below. 
2. Place a PlotView on Form1 and Dock to Fill. Name to plot1.
2. Make sure the mouse is over the series when the form starts.  May need to try a few times to get mouse placement correct.

To be clear, this is not a problem only seen on app startup, but on the creating of any form with a plotview and with a LineSeires where using its ItemSource property and binding to mouse enter in the PlotController.
I have an app where I have a user input info in a GUI and when they click the ok button, a new form with a PlotView as described above is created. If the mouse is over the PlotView when the form is being show, the error occurs.  Except this time, the error occurs even if not directly over the series, as long as its over the PlotView.
Even when not binding to mouse enter, this also happens on the right click event if the mouse is right clicked fast enough after clicking the ok button, although I can't reproduce this in the code example below.
I'm sure there are other situations but the solution is probably going to be the same for all.

I tried moving the construction of the PlotController to the forms Shown event but this didnt help.

Platform:
.NET version: 4.8

### Expected behavior

Should not crash.

### Actual behavior

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: source
  Source=System.Core
  StackTrace:
   at System.Linq.Enumerable.Skip[TSource](IEnumerable`1 source, Int32 count)
   at OxyPlot.Series.XYAxisSeries.GetNearestPointInternal(IEnumerable`1 points, Int32 startIdx, ScreenPoint point)
   at OxyPlot.Series.DataPointSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate)
   at OxyPlot.Series.LineSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate)
   at OxyPlot.PlotModel.GetSeriesFromPoint(ScreenPoint point, Double limit)
   at OxyPlot.TrackerManipulator.Started(OxyMouseEventArgs e)
   at OxyPlot.ControllerBase.AddHoverManipulator(IView view, ManipulatorBase`1 manipulator, OxyMouseEventArgs args)
   at OxyPlot.PlotCommands.<>c.<.cctor>b__0_13(IPlotView view, IController controller, OxyMouseEventArgs args)
   at OxyPlot.DelegatePlotCommand`1.<>c__DisplayClass0_0.<.ctor>b__0(IView v, IController c, T e)
   at OxyPlot.DelegateViewCommand`1.Execute(IView view, IController controller, OxyInputEventArgs args)
   at OxyPlot.ControllerBase.HandleCommand(IViewCommand command, IView view, OxyInputEventArgs args)
   at OxyPlot.ControllerBase.HandleMouseEnter(IView view, OxyMouseEventArgs args)
   at OxyPlot.WindowsForms.PlotView.OnMouseEnter(EventArgs e)
   at System.Windows.Forms.Control.WmMouseEnter(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SendMessage(HandleRef hWnd, Int32 msg, Int32 wParam, Int32 lParam)
   at System.Windows.Forms.Control.SendMessage(Int32 msg, Int32 wparam, Int32 lparam)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at WindowsFormsOxyTest.Program.Main() in C:\Users\myname\source\repos\WindowsFormsOxyTest\WindowsFormsOxyTest\Program.cs:line 19
```

Similar behavior to issue #1208 

### Suggested solution
Not sure, maybe add null checking.

### Example Code

```C#
using OxyPlot;
using OxyPlot.Series;
using System;
using System.Collections.Generic;
using System.Windows.Forms;

namespace WindowsFormsOxyTest
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

        private static int n = 100000;

        public static PlotModel UsingIDataPointProvider()
        {
            var points = new List<PointType1>(n);
            for (int i = 0; i < n; i++)
            {
                var x = (double)i / (n - 1);
                points.Add(new PointType1(x, y(x)));
            }

            var model = new PlotModel { Title = "Items implementing IDataPointProvider" };
            model.Series.Add(new LineSeries { ItemsSource = points });
            return model;
        }

        private class PointType1 : IDataPointProvider, ICodeGenerating
        {
            public PointType1(double abscissa, double ordinate)
            {
                this.Abscissa = abscissa;
                this.Ordinate = ordinate;
            }

            public double Abscissa { get; private set; }

            public double Ordinate { get; private set; }

            public DataPoint GetDataPoint()
            {
                return new DataPoint(Abscissa, Ordinate);
            }

            public string ToCode()
            {
                return CodeGenerator.FormatConstructor(this.GetType(), "{0},{1}", this.Abscissa, this.Ordinate);
            }
        }

        /// <summary>
        /// Evaluates a chaotic function.
        /// </summary>
        /// <param name="x">The x value.</param>
        /// <returns>A y value.</returns>
        private static double y(double x)
        {
            // http://computing.dcu.ie/~humphrys/Notes/Neural/chaos.html
            return Math.Sin(3 / x) * Math.Sin(5 / (1 - x));
        }
    }
}
```

```C#
using OxyPlot;
using System.Windows.Forms;

namespace WindowsFormsOxyTest
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            WindowState = FormWindowState.Maximized;

            plot1.Model = Program.UsingIDataPointProvider();

            var myController = new PlotController();
            plot1.Controller = myController;
            myController.BindMouseEnter(PlotCommands.HoverSnapTrack);
        }
    }
}
```

**Comment by Corey11820** [comment]
Apologies if the Oxy team already knows why this is happening but after a little digging this is what I got… 

`DataPointSeries.GetNearestPoint` contains a method call to `GetNearestPointInternal` which has `ActualPoints` as a parameter. `ActualPoints` returns null even though the `ItemSource` is not null.  This is because `itemsSourcePoints` is null.
This explains why this happens only when using the series `ItemSource` property, otherwise `ActualPoints` will return `points` which may contain the points or at worst contain 0 points, but the point is (pun intended) it will not return null.  Of course this null gets passed down to `XYAxisSeries.GetNearestPointInternal` where the exception occurs in the `Enumerable.Skip`

![Screenshot 2022-02-03 103311](https://user-images.githubusercontent.com/88932957/152374555-33214d7b-1ed3-40a3-b60c-0211e2f430a4.png)

The question remains, why is `itemsSourcePoints` null?
It appears that `itemsSourcePoints` is not updated until `UpdateItemsSourcePoints` is called by `UpdateData`.  `UpdateData` is called in `PlotModel.Update`, which is called by the `PlotView.OnPaint` method.  If a event occurs that in turn has a call stack to `DataPointSeries.GetNearestPoint`, which continues to `XYAxisSeries.GetNearestPointInternal` where the exception occurs at `points.Skip`, before the `OnPaint` event is called, this error will happen. Since the first call I see to `UpdateData` is in `OnPaint`

As far as a solution, I’ll have to leave that up to the Oxy team, or more capable programmers than me, to decide but here are some of my ideas…

1. In Plotview.cs, override `WnpProc` and on m.msg 129 (WM_NCCREATE) call the `UpdateData` method.  This will make sure `itemsSourcePoints` is not null when the mouse, or other, event fires.  On testing I noticed a down side. If the enter event is bound to `HoverSnapTrack`, as in my example, and the mouse is over the plot when the form is created, it does take a bit longer to display the data the first time.  I don’t like this approach because of this.
2. It might be well enough to just to add null checking in `GetNearestPointInternal`.
3. Can add a flag and set it on `OnPaint`.  On events, check if the flag has been set and ignore event if not.  Not sure if this feels right but it works quite well and there is pretty much no performance penalty.  Is there any reason for events to fire if the control hasn’t been painted for the first time?
4. Other?

**Comment by VisualMelon** [comment]
No need to apologize; on the contrary, thinks for digging into this!

Option 2 sounds like a reasonable thing to do in any case, but it may also makes sense to reject input at a higher level if the plot isn't updated.

**Comment by jonnyb023** [comment]
Also having this issue.  To me the easiest fix might be to just instantiate the `itemsSourcePoints` declaration in `DataPointSeries`.  Otherwise I have to do one of the following:

1. Call `UpdateData()` after setting `ItemsSource`
2. Override `GetNearestPoint()` and add null-checking for `ActualPoints` (essentially the same as Option 2 above)

**Comment by qcwat** [comment]
I also had this issue in the 2.2.0 release.  Instantiating `itemsSourcePoints` to an empty list seems like the best fix to me, as @jonnyb023 suggested.

As a workaround (so I could keep using the formal release), I had to derive a new local class from `LineSeries` and override `GetNearestPoint()` with the null check (item 2. above).
