### ISSUE TITLE
The specified Visual is not an ancestor of this Visual.

### ISSUE THREAD

**Issue by kevkon3** [oxyplot/oxyplot#325]
I am trying out some WPF docking code (see http://www.actiprosoftware.com/products/controls/wpf/docking) and I am attempting to put a PlotView into a docking container. Everything works fine until I try to move the docking window to a new place.

I get a message of "The specified Visual is not an ancestor of this Visual." and stacktrace (copied below).

I took a look at IsUserVisible(FrameworkElement element, FrameworkElement container) in PlotBase. It checks to see if the element (I assume the plot) is visible, but not the container (I assume the docking window). My guess is that the docking windows briefly becomes invisible as it is moved to a new location. Perhaps adding a check to see if the container is visible would fix the issue?
   
   at System.Windows.Media.Visual.TrySimpleTransformToAncestor(Visual ancestor, Boolean inverse, GeneralTransform& generalTransform, Matrix& simpleTransform)
   at System.Windows.Media.Visual.InternalTransformToAncestor(Visual ancestor, Boolean inverse)
   at OxyPlot.Wpf.PlotBase.IsUserVisible(FrameworkElement element, FrameworkElement container) in c:\projects\oxyplot\Source\OxyPlot.Wpf\PlotBase.cs:line 450
   at OxyPlot.Wpf.PlotBase.IsVisibleToUser() in c:\projects\oxyplot\Source\OxyPlot.Wpf\PlotBase.cs:line 427
   at OxyPlot.Wpf.PlotBase.OnLayoutUpdated(Object sender, EventArgs e) in c:\projects\oxyplot\Source\OxyPlot.Wpf\PlotBase.cs:line 493
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at ActiproSoftware.Windows.Controls.Docking.DockSite.RaftCore(#ki notifier, DependencyObject control, Nullable`1 position, Nullable`1 size, FloatSizingBehavior behavior, Boolean isDrag)
   at ActiproSoftware.Windows.Controls.Docking.DockSite.Raft(DependencyObject control, Nullable`1 position, Nullable`1 size, FloatSizingBehavior behavior, Boolean isDrag)
   at ActiproSoftware.Windows.Controls.Docking.DockSite.Raft(DependencyObject control, Nullable`1 position, Boolean isDrag)
   at ActiproSoftware.Windows.Controls.Docking.Primitives.RaftableDockingWindowContainer.OnPreviewWindowExitMove(Object sender, DockingPreviewEventArgs e)
   at #oi.#si.#tw(DockingPreviewEventArgs #yhb)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by kevkon3** [comment]
I just tried adding a check for in IsUserVisible for !container.IsVisible.

    if (!container.IsVisible || !element.IsVisible)
    {
        return false;
    }

That did the trick. I guess I'll make a small pull request for this.
